apiVersion: v1
kind: Service
metadata:
  name: flask-cicd-jenkins
spec:
  type: NodePort
  selector:
    app: flask-cicd-jenkins
  ports:
  - protocol: TCP
    port: 5000
    nodePort: 31000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-cicd-jenkins
  labels:
    app: flask-cicd-jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-cicd-jenkins
  template:
    metadata:
      labels:
        app: flask-cicd-jenkins
    spec:
      containers:
      - name: flask-cicd-jenkins
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        # image: esmejia277/flask-cicd-jenkins:2.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000